name = "auth0-customdb"
main = "src/index.ts"
compatibility_date = "2025-05-22"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "auth0_users"
database_id = "29a90f38-5b25-4362-9c15-6f5349ef4691" # update to your database ID after `wrangler d1 create auth0_users`

[observability]
enabled = true
head_sampling_rate = 1