name = "auth0-customdb"
main = "src/index.ts"
compatibility_date = "2025-05-22"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "auth0_users"
database_id = "49aec7c8-157c-4a7c-a911-5a7f19223cfd" # update to your database ID after `wrangler d1 create auth0_users`

[observability]
enabled = true
head_sampling_rate = 1